import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const isProd = process.argv[2] === "production";

// Flip to `true` (or set DEBUG_LOGS=1 in the env) to re-enable the
// verbose [worker]/[cache]/[manager] console logs and Notice toasts
// used for diagnosing model-loading issues.  Off by default so the
// shipped plugin stays quiet; esbuild dead-code-eliminates the
// guarded branches when this is the constant `false`.
const debugLogs = process.env.DEBUG_LOGS === "1" || process.env.DEBUG_LOGS === "true";

const sharedConfig = {
	bundle: true,
	logLevel: "info",
	sourcemap: isProd ? false : "inline",
	treeShaking: true,
	minify: isProd,
	target: "es2020",
};

const workerConfig = {
	...sharedConfig,
	entryPoints: ["src/transcription/worker.ts"],
	format: "esm",
	outfile: "worker.js",
	platform: "browser",
	banner: {
		// Shadow Electron's global `process` on the worker's own scope.
		// Both Transformers.js and the external ort-wasm-simd-threaded
		// .mjs files detect Node.js via different checks:
		//   - Transformers.js: process?.release?.name === "node"
		//   - ort .mjs files:  typeof process.versions.node === "string"
		// If either is true, they import Node-only modules (onnxruntime-node,
		// worker_threads) that fail in the blob-URL worker context.
		// Removing `release.name` and `versions` forces both libraries to
		// take the browser code path. This is safe because the worker is an
		// isolated blob-URL context — the main thread's process is unaffected.
		js: `if(typeof process!=="undefined"){self.process={...process,release:{...process.release,name:""},versions:{}};}`
	},
	define: {
		"process.env.NODE_ENV": isProd ? '"production"' : '"development"',
		DEBUG_LOGS: String(debugLogs),
	},
};

function readWorkerBase64() {
	const workerCode = fs.readFileSync("worker.js", "utf-8");
	return Buffer.from(workerCode).toString("base64");
}

function mainDefines() {
	return {
		WORKER_BASE64: JSON.stringify(readWorkerBase64()),
		DEBUG_LOGS: String(debugLogs),
	};
}

const mainExternals = [
	"obsidian",
	"electron",
	"@codemirror/autocomplete",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/view",
	"@lezer/common",
	"@lezer/highlight",
	"@lezer/lr",
	...builtins,
];

if (isProd) {
	// Production: build worker, inline into main, done.
	await esbuild.build(workerConfig);
	await esbuild.build({
		...sharedConfig,
		banner: { js: banner },
		entryPoints: ["src/main.ts"],
		external: mainExternals,
		format: "cjs",
		outfile: "main.js",
		define: mainDefines(),
	});
	process.exit(0);
} else {
	// Dev: rebuild worker first, then watch both.
	// When the worker changes, rebuild it and then rebuild main.js
	// so the inlined Base64 stays current.
	await esbuild.build(workerConfig);

	const mainContext = await esbuild.context({
		...sharedConfig,
		banner: { js: banner },
		entryPoints: ["src/main.ts"],
		external: mainExternals,
		format: "cjs",
		outfile: "main.js",
		define: mainDefines(),
	});

	const workerContext = await esbuild.context({
		...workerConfig,
		plugins: [{
			name: "rebuild-main-on-worker-change",
			setup(build) {
				build.onEnd(async (result) => {
					if (result.errors.length === 0) {
						// Worker changed — rebuild main with fresh Base64
						await mainContext.cancel();
						await mainContext.dispose();
						const freshMain = await esbuild.context({
							...sharedConfig,
							banner: { js: banner },
							entryPoints: ["src/main.ts"],
							external: mainExternals,
							format: "cjs",
							outfile: "main.js",
							define: mainDefines(),
						});
						await freshMain.rebuild();
						await freshMain.watch();
					}
				});
			},
		}],
	});

	await workerContext.watch();
	await mainContext.watch();
}
