import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const isProd = process.argv[2] === "production";

const sharedConfig = {
	bundle: true,
	logLevel: "info",
	sourcemap: isProd ? false : "inline",
	treeShaking: true,
	minify: isProd,
	target: "es2020",
};

// Pass 1: Main plugin bundle (CJS for Obsidian)
const mainContext = await esbuild.context({
	...sharedConfig,
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	outfile: "main.js",
});

// Pass 2: Worker bundle (ESM, self-contained, browser platform)
const workerContext = await esbuild.context({
	...sharedConfig,
	entryPoints: ["src/transcription/worker.ts"],
	format: "esm",
	outfile: "worker.js",
	platform: "browser",
	define: {
		"process.env.NODE_ENV": isProd ? '"production"' : '"development"',
		// Force Transformers.js to use the browser/WASM code path.
		// In Obsidian's Electron, process.release.name === "node" which
		// makes IS_NODE_ENV true, causing it to import onnxruntime-node
		// (shimmed to empty) instead of onnxruntime-web. This breaks
		// ONNX.Tensor with "Right-hand side of instanceof is not an object".
		"process.release": "undefined",
	},
});

if (isProd) {
	await Promise.all([mainContext.rebuild(), workerContext.rebuild()]);
	await Promise.all([mainContext.dispose(), workerContext.dispose()]);
	process.exit(0);
} else {
	await Promise.all([mainContext.watch(), workerContext.watch()]);
}
